"""
Comprehensive test suite to validate OPT generation fixes.

This script tests all failing cases and validates that:
1. The MathML is correctly generated by latexmlmath
2. The CMML can be isolated
3. The SemanticSymbol can parse the CMML
4. The resulting tree has expected structure
"""

import sys
from pathlib import Path
from collections import defaultdict

# Add src directory to path
sys.path.insert(0, str(Path(__file__).parent / 'src'))

from multirag.formula_search.latex_mml import LatexToMathML
from multirag.formula_search.math_extractor import MathExtractor
from multirag.formula_search.exceptions import UnknownTagException

# Test cases organized by issue type
TEST_CASES = {
    "share_elements": [
        (r"R^2 = 2 = \frac{Q^2}{D^2}", "chained equality with fractions"),
        (r"2^{1-1} = 2^1 / 2^1 = 2/2 = 1", "chained equality with powers"),
        (r"a^2 / a^3 = a^{-1} = 1/a", "chained equality with negative exponent"),
        (r"1.000\ldots -.99999\ldots = .000\ldots = 0", "chained equation with ellipsis"),
        (r"a = CE = L/R=2\sin(\theta)", "chained equation with functions"),
        (r"\frac{\frac{9}{10}}{1 - \frac{1}{10}} = \frac{\frac{9}{10}}{\frac{9}{10}} = 1.", "nested fractions in chained equation"),
        (r"0.9999... < x < 1", "chained inequality"),
    ],
    "conditional_operator": [
        (r"k|n", "simple divisibility"),
        (r"p|(10^k-1)", "divisibility with power"),
        (r"k|(p-1)", "divisibility with subtraction"),
        (r"P(X_n | X_1, X_2, \dots X_{n-1}) = P(X_n | X_{n-1})", "conditional probability"),
    ],
    "differential_operator": [
        (r"\langle \, f, \, g \, \rangle = \int_a^b \ f(x)\overline{g(x)} \, dx", "inner product with integral"),
        (r"\int e^x dx=e^x+c", "exponential integral"),
        (r"\displaystyle\int \frac{1}{x} dx=\ln x", "logarithmic integral"),
    ],
    "already_working": [
        (r"x^2 + y", "simple addition"),
        (r"x^2", "simple power"),
    ]
}

class OPTTestRunner:
    """Test suite for OPT generation."""
    
    def __init__(self):
        self.results = defaultdict(list)
        self.passed = 0
        self.failed = 0
        
    def test_formula(self, formula, description, issue_category):
        """Test a single formula."""
        result = {
            'formula': formula,
            'description': description,
            'category': issue_category,
            'passed': False,
            'error': None,
            'error_type': None,
        }
        
        try:
            # Generate MathML
            mathml = LatexToMathML.convert_to_mathml2(formula)
            
            # Isolate CMML
            cmml = MathExtractor.isolate_cmml(mathml)
            
            # Convert to semantic symbol
            symbol_root = MathExtractor.convert_to_semanticsymbol(cmml)
            
            if symbol_root is None:
                result['error'] = "convert_to_semanticsymbol returned None"
                result['error_type'] = "NoneError"
            else:
                result['passed'] = True
                self.passed += 1
                
        except UnknownTagException as e:
            result['error'] = str(e)
            result['error_type'] = "UnknownTagException"
            self.failed += 1
        except Exception as e:
            result['error'] = str(e)
            result['error_type'] = type(e).__name__
            self.failed += 1
        
        self.results[issue_category].append(result)
        return result
    
    def run_all_tests(self):
        """Run all test cases."""
        print("\n" + "="*100)
        print("OPT PARSING TEST SUITE")
        print("="*100)
        
        for category, test_list in TEST_CASES.items():
            print(f"\n\n{'='*100}")
            print(f"Testing: {category.upper()}")
            print(f"{'='*100}")
            
            for formula, description in test_list:
                result = self.test_formula(formula, description, category)
                status = "✓ PASS" if result['passed'] else "✗ FAIL"
                print(f"\n{status} | {description}")
                print(f"      Formula: {formula[:70]}{'...' if len(formula) > 70 else ''}")
                if result['error']:
                    print(f"      Error: {result['error'][:80]}{'...' if len(result['error']) > 80 else ''}")
        
        self.print_summary()
    
    def print_summary(self):
        """Print test summary."""
        print("\n\n" + "="*100)
        print("TEST SUMMARY")
        print("="*100)
        
        total = self.passed + self.failed
        pass_rate = (self.passed / total * 100) if total > 0 else 0
        
        print(f"\nTotal Tests: {total}")
        print(f"Passed: {self.passed}")
        print(f"Failed: {self.failed}")
        print(f"Pass Rate: {pass_rate:.1f}%")
        
        print("\n" + "-"*100)
        print("Results by Category:")
        print("-"*100)
        
        for category in sorted(self.results.keys()):
            tests = self.results[category]
            passed = sum(1 for t in tests if t['passed'])
            total = len(tests)
            print(f"\n{category}: {passed}/{total} passed")
            
            # Show failures in this category
            failures = [t for t in tests if not t['passed']]
            if failures:
                for failure in failures:
                    print(f"  ✗ {failure['description']}")
                    print(f"    {failure['error_type']}: {failure['error'][:60]}...")
        
        print("\n" + "-"*100)
        print("Error Summary:")
        print("-"*100)
        
        error_counts = defaultdict(int)
        for category_results in self.results.values():
            for result in category_results:
                if not result['passed']:
                    error_counts[result['error_type']] += 1
        
        for error_type, count in sorted(error_counts.items(), key=lambda x: -x[1]):
            print(f"  {error_type}: {count} occurrences")
        
        print("\n" + "="*100 + "\n")


def main():
    """Run the test suite."""
    runner = OPTTestRunner()
    runner.run_all_tests()
    
    # Exit with appropriate code
    return 0 if runner.failed == 0 else 1


if __name__ == '__main__':
    exit_code = main()
    sys.exit(exit_code)
